version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin <account-id>.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker images..."
      - ./scripts/docker_build.sh
      - echo "Pushing Docker images to ECR..."
      - ./scripts/docker_push.sh
  post_build:
    commands:
      - echo "Deploying to EKS..."
      - ./scripts/kubernetes_deploy.sh
